name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/setup-node@v1
        with:
        node-version: '12.16.0'

      - name: install leiningen
        uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.8.3

      - name: install deps
        run: lein deps

      - name: clean
        run: lein clean

      - name: build
        run: lein cljsbuild once min

      - name: deploy to gh pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./resources/public
